### PR TITLE
feat(SDK-6047): Multi-instance support — per-account handles, events, and launch configs

### PR DESCRIPTION
**Pull request by piyush-kukadiya**
Jira: SDK-6047

Adds full multi-instance (multi-account) support to the React Native SDK: an app can create and use additional CleverTap accounts from JavaScript, with per-account events, listeners, variables, custom templates, and push-permission flows.

## What an app can do now

```js
// Create an extra account (or fetch config from your server first):
const ctB = await CleverTap.createInstance({ accountId, accountToken, accountRegion });
ctB.recordEvent('Purchase');
ctB.addListener(CleverTap.CleverTapPushNotificationClicked, onClick);

// The top-level CleverTap object keeps addressing the manifest/plist default account.
CleverTap.recordEvent('Open');
```

- ~112 methods are routed per account on both the top-level object and handles; handles are frozen, memoized per accountId.
- Events demux per account in JS; every native payload carries an internal account tag that is stripped before user code sees it.
- Custom templates present/resolve per account on both platforms.
- Accounts that must catch launch-time events (the push tap that cold-starts the app) can be pre-created natively via `initReactNativeIntegration(context, launchConfigs)` (Android) / `applicationDidLaunchWithOptions:launchConfigs:` (iOS), then used from JS with `getInstance(accountId)` — including an optional per-account custom CleverTap ID.

## Bugs fixed along the way

- Event buffers rewritten to be account-aware AND thread-safe: one monitor per buffer, atomic buffer/send decision, drain under the lock but send outside it. Supersedes and extends the SDK-6021 fix; a 50k-iteration race test that reproduces the production `NoSuchElementException` on the old code is included as a JVM unit test.
- iOS `setLocation` misroute; iOS pending-events statics race (main-queue confinement); JS demux crash on string payloads.
- `createInstance` now applies the passed config on every fresh launch (matches native semantics); previously a stale persisted config could be resurrected.
- Notification channels, `createNotification`, and the push-permission trio work in apps with no manifest/plist account; iOS `isPushPermissionGranted` completes its callback with an error instead of hanging when no instance exists.
- Wrapper name/version is stamped on every JS-created instance, not just the default.
- Per-account variables registry (two accounts defining the same variable name no longer overwrite each other), with null guards for ConcurrentHashMap semantics.

## Compatibility

- Public JS API is backward compatible: all existing top-level calls behave as before, addressing the default account.
- Direct `NativeModules.CleverTapReact` callers on the OLD architecture are affected: ~120 native method signatures gained a trailing `accountId` argument. Apps using the documented `CleverTap` JS module are unaffected.
- `initReactNativeIntegration` keeps its one-argument form (`@JvmOverloads`); the iOS manager keeps the existing `applicationDidLaunchWithOptions:`.

## Testing

- JVM unit tests for the event emitter, including the SDK-6021 race reproduction (fails on the old code, passes now).
- Build gates on every commit: Android compile on BOTH architectures, Android unit tests, iOS `pod install` + `xcodebuild` (BUILD SUCCEEDED), `tsc` on the typings, eslint (no new issues), Metro release bundle.
- Rebased onto develop after v4.3.1; verified the 4.3.1 fixes survived: prompt trio still hops to the main thread (SDK-6004), variables registry stays concurrent with null guards, event-buffer locking is covered by the per-buffer monitor design.
- Example app demos each new API (multi-instance actions, per-account templates; commented launch-config blocks in MainApplication/AppDelegate).
- Still pending before release: on-device old-architecture runtime smoke test, cold-start push-tap verification for launch-listed accounts, docs/CHANGELOG (tracked separately).

🤖 Generated with [Claude Code](https://claude.com/claude-code)

## Summary by CodeRabbit

* **New Features**
  * Added multi-account support for creating and accessing separate CleverTap instances.
  * Added account-specific event, profile, inbox, messaging, personalization, variables, and custom-template operations.
  * Added launch-time account configuration for cold-start event handling.
  * Added removable event-listener subscriptions and account-specific event routing.
  * Added account-aware custom-template presentation and interaction handling.
* **Bug Fixes**
  * Improved event buffering and delivery to prevent events from being sent to the wrong account.
  * Improved handling of account-specific callbacks, queued events, and initialization errors.
  * Added clearer validation for invalid instance configuration values.

### CODE REVIEW

**Comment by shubhambjadhavar** [comment]
### :no_entry: **Snyk checks have failed. 1 issues have been found so far.**

| Status | Scan Engine |  Critical |  High |  Medium |  Low | Total (1) |
|---|---|---|---|---|---|---|
| :white_check_mark: | Open Source Security| 0 | 0 | 0 | 0 | [ 0 issues](https://app.snyk.io/org/clevertap-platform/pr-checks/4708ed23-0462-4a04-98b3-6c93d0ad2f85?refs=d1399eab35bcadf276574e305de27ee9548ceb35&source=prChecksComment) |
| :white_check_mark: | Licenses| 0 | 0 | 0 | 0 | [ 0 issues](https://app.snyk.io/org/clevertap-platform/pr-checks/4708ed23-0462-4a04-98b3-6c93d0ad2f85/license?refs=d1399eab35bcadf276574e305de27ee9548ceb35&source=prChecksComment) |
| :no_entry: | Code Security| 0 | 1 | 0 | 0 | [ 1 issues](https://app.snyk.io/org/clevertap-platform/project/a7a30ec8-c598-4c47-9430-2d60c9c4f8c9/pr-check/c209994c-2311-4658-9ced-dfe1b9d89ac1?refs=d1399eab35bcadf276574e305de27ee9548ceb35&source=prChecksComment) |

:computer: Catch issues earlier using the plugins for [VS Code](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner), [JetBrains IDEs](https://plugins.jetbrains.com/plugin/10972-snyk-security), [Visual Studio](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner-vs-2022), and [Eclipse](https://marketplace.eclipse.org/content/snyk-security#external-install-button).

File: src/index.js [hunk 1]
```diff
@@ -40,11 +51,551 @@ function callWithCallback(method, args, callback) {
...
+ * fired it, under CT_ACCOUNT_ID_KEY. A central "sorting office" (demux) below
+ * keeps ONE native subscription per event name, reads the tag, and re-delivers
+ * the event under a per-account key like 'ACCT_B::CleverTapProfileSync'. Each
+ * account handle subscribes to exactly its own key, so no handle is ever woken
+ * for another account's events.
+ * ------------------------------------------------------------------------- */
+
+// Defined once — no magic strings. Must match Constants.CT_ACCOUNT_ID_KEY (Android)
+// and kCleverTapAccountIdKey (iOS).
+const CT_ACCOUNT_ID_KEY = '__ctAccountId';
```
Comment (shubhambjadhavar) [inline src/index.js:76]: ### <sub></sub>&nbsp; Hardcoded Non-Cryptographic Secret

Avoid hardcoding values that are meant to be secret. Found `a hardcoded string` used in `here`.

<h6>
Line 76 | <a href="https://cwe.mitre.org/data/definitions/547.html">CWE-547</a> | <a href="https://docs.snyk.io/manage-risk/prioritize-issues-for-fixing/priority-score">Priority score 650</a> | <a href="https://learn.snyk.io/lesson/hardcoded-secrets/?source=code-pr&utm_campaign=snyk-learn&utm_medium=inline-comment&utm_source=npx">Learn more about this vulnerability</h6>

<details>

<summary>Data flow: 2 steps</summary>

`Step 1 - 2` https://github.com/CleverTap/clevertap-react-native/blob/f63df226cf82ad69d483a103fdcfe064b6928524/src/index.js#L76

</details>

Comment (piyush-kukadiya) [reply src/index.js:76]: Its just a lable and not secret

File: ios/CleverTapReact/CleverTapReact.mm [hunk 2]
```diff
@@ -89,33 +109,211 @@ - (instancetype)init
...
+        instance = self.defaultInstance;
+    } else {
+        instance = [CleverTap getGlobalInstance:accountId];
+    }
+
+    if (instance == nil) {
+        // The ONE warning that covers every bridge method (same rule as Android):
+        // without it a typo'd accountId silently drops every call.
+        if (accountId == nil) {
+            RCTLogWarn(@"CleverTap default instance is not available — call ignored");
```
Comment (nishant-clevertap) [inline ios/CleverTapReact/CleverTapReact.mm:143]: can you confirm if this if condition will be executed in any case?

File: ios/CleverTapReact/CleverTapReact.mm [hunk 3]
```diff
@@ -89,33 +109,211 @@ - (instancetype)init
...
+    // Without this, useCustomCleverTapId=true would create an instance that waits
+    // for an ID nobody can ever provide (error device id).
+    NSString *cleverTapId = config[@"cleverTapId"];
+    // Instance creation can THROW, not just return nil: registered custom template
+    // producers run inside it, and e.g. duplicate template names raise NSException
+    // (CleverTapCustomTemplateException). An uncaught throw would crash the app
+    // instead of rejecting the promise.
+    CleverTap *instance;
+    @try {
+        instance = (cleverTapId.length > 0)
```
Comment (nishant-clevertap) [inline ios/CleverTapReact/CleverTapReact.mm:290]: what if useCustomCleverTapId is not provided in config and cleverTapId is provided?

File: ios/CleverTapReact/CleverTapReact.mm [hunk 4]
```diff
@@ -1338,46 +1665,106 @@ - (void)resolveWithTemplateContext:(NSString *)templateName
...
     if (pendingEventsForName) {
         RCTLogInfo(@"[CleverTap: Posting pending events for event: %@]", name);
+        NSMutableArray<CleverTapReactPendingEvent *> *remaining = [NSMutableArray array];
         for (CleverTapReactPendingEvent *event in pendingEventsForName) {
-            RCTLogInfo(@"[CleverTap: posting pending event: %@ with body: %@]", event.name, event.body);
-            [[NSNotificationCenter defaultCenter] postNotificationName:event.name object:nil userInfo:event.body];
+            NSString *tag = accountTagOfBody(event.body);
+            if (tag == nil || (accountKey != nil && [tag isEqualToString:accountKey])) {
+                RCTLogInfo(@"[CleverTap: posting pending event: %@ with body: %@]", event.name, event.body);
+                [[NSNotificationCenter defaultCenter] postNotificationName:event.name object:nil userInfo:event.body];
```
Comment (nishant-clevertap) [inline ios/CleverTapReact/CleverTapReact.mm:1706]: can you confirm the body has correct template name as previous as I can see you have changed the body now contains keys kCleverTapPayloadKey, previously it was directly context.templateName.

This will be breaking change even if we add it in docs.

File: src/index.js [hunk 5]
```diff
@@ -302,52 +854,52 @@ var CleverTap = {
      * @returns {void}
  */
     setOptOut: function(userOptOut, allowSystemEvents = false) {
-        CleverTapReact.setOptOut(userOptOut, allowSystemEvents);
+        CleverTapReact.setOptOut(userOptOut, allowSystemEvents, null);
     },
 
     /**
     * Sets the CleverTap SDK to offline mode
     * @param {boolean} value - A boolean for enabling or disabling sending events for current user
```
Comment (nishant-clevertap) [inline src/index.js:862]: add doc comment for second argument here and everywhere else

File: ios/CleverTapReact/CleverTapReact.mm [hunk 6]
```diff
@@ -131,14 +329,16 @@ - (void)setCleverTapInstance:(CleverTap *)instance {
...
     [[self cleverTapInstance] setLibrary:name];
     [[self cleverTapInstance] setCustomSdkVersion:name version:libVersion];
 }
 
-RCT_EXPORT_METHOD(setLocale:(NSString*)locale) {
+RCT_EXPORT_METHOD(setLocale:(NSString*)locale accountId:(NSString*)accountId) {
     RCTLogInfo(@"[CleverTap setLocale:%@]", locale);
     NSLocale *userLocale = [NSLocale localeWithLocaleIdentifier:locale];
-    [[self cleverTapInstance] setLocale:userLocale];
+    [[self resolveInstance:accountId] setLocale:userLocale];
```
Comment (nishant-clevertap) [inline ios/CleverTapReact/CleverTapReact.mm:341]: I can see [self resolveInstance:accountId] method can return nil, so calling native ios methods on nil may leads to crash, we have to write guard nil check everywhere this is used. please verify this and make changes if needed at this place and other places also

File: ios/CleverTapReact/CleverTapReact.mm [hunk 7]
```diff
@@ -850,138 +1107,138 @@ - (void)messageDidSelect:(CleverTapInboxMessage *_Nonnull)message atIndex:(int)i
...
+    [[self resolveInstance:accountId] unmute];
 }
 
 #pragma mark - InApp Controls
 
-RCT_EXPORT_METHOD(fetchInApps:(RCTResponseSenderBlock)callback) {
+RCT_EXPORT_METHOD(fetchInApps:(NSString*)accountId callback:(RCTResponseSenderBlock)callback) {
     RCTLogInfo(@"[CleverTap fetchInApps]");
-    [[self cleverTapInstance] fetchInApps:^(BOOL success) {
+    [[self resolveInstance:accountId] fetchInApps:^(BOOL success) {
```
[the remark this answers is not in the document]
Comment (nishant-clevertap) [reply ios/CleverTapReact/CleverTapReact.mm:1234]: @piyush-kukadiya check this seems important

File: src/NativeCleverTapModule.ts [hunk 8]
```diff
@@ -154,103 +214,158 @@ export interface Spec extends TurboModule {
...
-  pushInboxNotificationClickedEventForId(messageId: string): void;
-  markReadInboxMessageForId(messageId: string): void;
-  deleteInboxMessageForId(messageId: string): void;
-  markReadInboxMessagesForIDs(messageIds: string[]): void;
-  deleteInboxMessagesForIDs(messageIds: string[]): void;
-  dismissInbox(): void;
-  initializeInbox(): void;
-  fetchInbox(callback: ((error: Object, result: boolean) => void) | null): void;
+  getInboxMessageCount(
+    accountId: string | null,
```
Comment (nishant-clevertap) [inline src/NativeCleverTapModule.ts:218]: why accountId is not optional here and at some places below?

File: ios/CleverTapReact/CleverTapReact.mm (hunk 6 above)
Comment (piyush-kukadiya) [reply ios/CleverTapReact/CleverTapReact.mm]: @nishant-clevertap Good catch — I verified every `resolveInstance:` call site. Two findings:

**1. No crash is possible.** In Objective-C, calling a method on `nil` is a silent no-op (unlike Java's `NullPointerException`): the call is skipped, a number result is `0`, an object result is `nil`. So `[[self resolveInstance:accountId] setLocale:userLocale]` with a missing account was already crash-safe.

**2. But three methods DID have a real bug.** `fetchInApps:`, `fetchInboxWithCallback:` and `fetchVariables:` take a completion block. Skipping the call skips the block, so the JS callback never fired and an awaiting caller hung forever (Android correctly answered with an error).

Fixed in https://github.com/CleverTap/clevertap-react-native/pull/522/commits/68ff7d9b5d6f57f49ba651e7df9e767964d830f5: every bridge method now goes through one of two helpers, so the missing-account rule lives in one place instead of ~90 call sites:
- `withInstance:run:` — fire-and-forget methods; the call is dropped (the one warning is already logged by `resolveInstance:`).
- `withInstance:callback:run:` — callback methods; the callback is completed with `"CleverTap is not initialized"` (same as Android).

File: ios/CleverTapReact/CleverTapReact.mm (hunk 7 above)
[the remark this answers is not in the document]
Comment (piyush-kukadiya) [reply ios/CleverTapReact/CleverTapReact.mm]: @nishant-clevertap Fixed in https://github.com/CleverTap/clevertap-react-native/pull/522/commits/68ff7d9b5d6f57f49ba651e7df9e767964d830f5. `fetchInApps:`, `fetchInbox:` and `fetchVariables:` now complete the callback with `"CleverTap is not initialized"` when the account has no instance, so an awaiting JS caller can never hang. Rather than three local `if (instance == nil)` blocks, the check is the `withInstance:callback:run:` helper that every iOS callback method now uses (see the thread on `setLocale` for the full picture).

File: ios/CleverTapReact/CleverTapReact.mm [hunk 9]
```diff
@@ -276,31 +477,31 @@ - (void)setCleverTapInstance:(CleverTap *)instance {
     [self returnResult:result withCallback:callback andError:nil];
 }
 
-RCT_EXPORT_METHOD(getUserEventLog:(NSString*)eventName callback:(RCTResponseSenderBlock)callback) {
+RCT_EXPORT_METHOD(getUserEventLog:(NSString*)eventName accountId:(NSString*)accountId callback:(RCTResponseSenderBlock)callback) {
     RCTLogInfo(@"[CleverTap getUserEventLog: %@]", eventName);
     dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
-        CleverTapEventDetail *detail = [[self cleverTapInstance] getUserEventLog:eventName];
+        CleverTapEventDetail *detail = [[self resolveInstance:accountId] getUserEventLog:eventName];
```
[the remark this answers is not in the document]
Comment (piyush-kukadiya) [reply ios/CleverTapReact/CleverTapReact.mm]: Fixed in https://github.com/CleverTap/clevertap-react-native/pull/522/commits/68ff7d9b5d6f57f49ba651e7df9e767964d830f5. `getUserEventLog`, `getUserEventLogCount`, `getUserEventLogHistory` and `getUserAppLaunchCount` now resolve the instance on the main queue (via `withInstance:callback:run:`) and capture it into the background block; `resolveInstance:` is no longer called from the global queue.

File: ios/CleverTapReact/CleverTapReact.mm (hunk 2 above)
Comment (piyush-kukadiya) [reply ios/CleverTapReact/CleverTapReact.mm:153]: @nishant-clevertap Yes, it runs whenever the app has no default account. `[CleverTap sharedInstance]` returns `nil` when `Info.plist` has no `CleverTapAccountID` / `CleverTapToken` (first check in `_sharedInstanceWithCleverTapID:`, `CleverTap.m`, SDK 7.8.1). That is a supported setup with multi-instance: an app that creates all its accounts from JS via `createInstance` and has nothing in the plist. If such an app calls a top-level method like `CleverTap.recordEvent(...)`, the default slot resolves to `nil`, this warning prints, and the call is dropped — without it the drop would be silent. Same as Android's `getDefaultInstance()` returning `null` without manifest credentials.

Where this lives in the history: the branch was added with `resolveInstance:` in https://github.com/CleverTap/clevertap-react-native/pull/522/commits/980ab24c1947af7763823f1db1b304bc2e525ac2, and as of https://github.com/CleverTap/clevertap-react-native/pull/522/commits/68ff7d9b5d6f57f49ba651e7df9e767964d830f5 every caller reacts to that `nil` through the `withInstance:run:` / `withInstance:callback:run:` helpers (drop the call, or complete the JS callback with an error).

File: ios/CleverTapReact/CleverTapReact.mm (hunk 3 above)
Comment (piyush-kukadiya) [reply ios/CleverTapReact/CleverTapReact.mm]: @nishant-clevertap Checked what both native SDKs actually do in that case (iOS 7.8.1 `CTDeviceInfo.m` line 187, Android 8.4.1 `DeviceInfo.java` line 928): the ID is **silently ignored** — the SDK logs "CleverTapUseCustomId has not been specified…", records a validation error and generates its own id. So the developer's `cleverTapId` is lost and every event lands under the wrong user, with no signal on the JS side. The reverse (`useCustomCleverTapId: true` without an id) leaves the account on an "error device id". React Native also has no later repair path (native can still pass the id via `onUserLogin(profile, cleverTapID)`; RN does not expose that).

Fixed in https://github.com/CleverTap/clevertap-react-native/pull/522/commits/eaff7513ebcf1b5e747b439d430773d6e41c1eb7: `createInstance` now rejects with `EINVALID` unless `cleverTapId` and `useCustomCleverTapId: true` are given together (or both left out), on both platforms — same fail-fast rule as an empty `accountId`/`accountToken`. Typings and JSDoc document the pairing. The native launch-config paths keep their warning, since at launch there is no promise to reject.

File: ios/CleverTapReact/CleverTapReact.mm (hunk 4 above)
Comment (piyush-kukadiya) [reply ios/CleverTapReact/CleverTapReact.mm:1940]: @nishant-clevertap Confirmed, the template name reaches app code unchanged. The wrapper `{__ctAccountId, __ctPayload: templateName}` is internal to the native→JS wire: a bare string cannot carry the account tag, so native wraps it and the JS demux (`routeEvent` in `src/index.js`) unwraps `__ctPayload` **before** any handler runs. `CleverTap.addListener(CleverTapCustomTemplatePresent, templateName => …)` still receives the plain string exactly as documented in `docs/CustomCodeTemplates.md`, and the Example app relies on that. The line here only replays the same wrapped body into the same demux, so pending events are unwrapped too. Android does the identical wrap (`CT_PAYLOAD_KEY` in `CleverTapCustomTemplates.kt`). The only code that would notice is an app subscribing to the raw `NativeEventEmitter` directly, which is undocumented and already called out in the PR description. Introduced in https://github.com/CleverTap/clevertap-react-native/pull/522/commits/7d33160cfacecf07495219bd08584457e92ca449 (see `routeEvent` in that commit).

File: src/index.js (hunk 5 above)
Comment (piyush-kukadiya) [reply src/index.js:872]: @nishant-clevertap Agreed that the bare `null` was unreadable. Instead of a comment at each of the ~110 call sites, https://github.com/CleverTap/clevertap-react-native/pull/522/commits/2640e59adf17046f655e45072591e31e2cc6f2b5 introduces one named constant `DEFAULT_ACCOUNT` (= `null`, "address the default account") with a single comment explaining why it must always be passed (the old-architecture Android bridge checks the exact argument count). Every top-level call now reads `CleverTapReact.setOffline(value, DEFAULT_ACCOUNT)`, and the handle path's `toAccountArg` uses the same constant, so there is one definition to maintain. No behavior change; eslint count and the Metro release bundle are unchanged.

File: src/NativeCleverTapModule.ts (hunk 8 above)
Comment (piyush-kukadiya) [reply src/NativeCleverTapModule.ts:227]: @nishant-clevertap Fair question — the mix was forced by TypeScript, not intended. On the bridge a callback must be the LAST argument, so in `getInboxMessageCount(accountId, callback)` the accountId comes first, and TypeScript rejects an optional parameter before a required one (`error TS1016: A required parameter cannot follow an optional parameter`). That is why only the callback-free methods could carry `?`.

The `?` was misleading anyway: JS never omits the argument (top-level calls pass `DEFAULT_ACCOUNT`, handles pass `toAccountArg(accountId)`), because the old-architecture Android bridge checks the exact argument count and throws on a missing trailing argument.

https://github.com/CleverTap/clevertap-react-native/pull/522/commits/5ee29ea051476014eeb768a3c3203a3990c19402 gives every method the same, honest shape `accountId: string | null` (required, nullable) plus one comment on the interface with the rule. No native impact — I regenerated codegen on both platforms and the generated `NativeCleverTapModuleSpec.java` and iOS `CTTurboModuleSpec` are byte-identical to before.

File: android/src/main/java/com/clevertap/react/CleverTapEventEmitter.kt [hunk 10]
```diff
@@ -2,102 +2,120 @@ package com.clevertap.react
...
+     * @see [flushBuffer]
      */
-    fun resetAllBuffers(enableBuffers: Boolean) {
-        eventsBuffers = createBuffersMap(enableBuffers)
-        Log.i(LOG_TAG, "Buffers reset and enabled: $enableBuffers")
+    fun armAccount(event: CleverTapEvent, accountId: String?) {
+        val buffer = eventsBuffers[event] ?: return
+        buffer.arm(accountId)
+        Log.i(LOG_TAG, "Armed $event for account $accountId")
     }
```
[the remark this answers is not in the document]
Comment (piyush-kukadiya) [reply android/src/main/java/com/clevertap/react/CleverTapEventEmitter.kt]: Fixed in https://github.com/CleverTap/clevertap-react-native/pull/522/commits/f1697ff364e9da0fd19c00565bd0f1a4c5849bda, by removing the shared state rather than adding a second lock. Every emitter operation (`emit`, `armAndFlush`, `resetAllBuffers`) is now posted to one single-thread worker (`Executors.newSingleThreadExecutor`, FIFO, sequential by contract), so "decide whether to buffer" and "send" happen in the same task and a flush sends its drained list in one task — a live same-account event can no longer overtake older buffered ones. `armAccount` + `flushBuffer` are merged into `armAndFlush`. No lock is held anywhere, so React Native is never called under one and no lock ordering exists to get wrong; callers only enqueue and never wait on the worker. A new ordering test (300 rounds, attach mid-stream, assert strict emit order) fails on the previous implementation and passes now; the SDK-6021 race test still passes.

File: android/src/oldarch/CleverTapModule.kt [hunk 11]
```diff
@@ -539,195 +550,220 @@ class CleverTapModule(reactContext: ReactApplicationContext?) :
...
 
     @ReactMethod
-    fun syncVariablesinProd(isProduction: Boolean, callback: Callback?) {
-        cleverTapModuleImpl.syncVariablesinProd(isProduction, callback)
+    fun syncVariablesinProd(isProduction: Boolean, accountId: String?) {
+        // Must match the spec's (isProduction, accountId) shape — the old-arch bridge
+        // checks the exact argument count. The impl's callback param is unused (no-op
+        // on Android), so pass null like the new-arch shim does.
+        cleverTapModuleImpl.syncVariablesinProd(isProduction, accountId)
     }
```
[the remark this answers is not in the document]
Comment (piyush-kukadiya) [reply android/src/oldarch/CleverTapModule.kt:682]: Fixed in https://github.com/CleverTap/clevertap-react-native/pull/522/commits/2166be96682a6c0c2325e02a7a28c9d4d2347759: the comment now describes the actual call, `(isProduction, accountId)`, and why it is a no-op on Android; the stale callback/null sentence is gone.

File: ios/CleverTapReact/CleverTapReact.mm [hunk 12]
```diff
@@ -164,108 +364,109 @@ - (void)setCleverTapInstance:(CleverTap *)instance {
...
 #pragma mark - Personalization
 
-RCT_EXPORT_METHOD(enablePersonalization) {
+RCT_EXPORT_METHOD(enablePersonalization:(NSString*)accountId) {
     RCTLogInfo(@"[CleverTap enablePersonalization]");
     [CleverTap enablePersonalization];
 }
 
-RCT_EXPORT_METHOD(disablePersonalization) {
+RCT_EXPORT_METHOD(disablePersonalization:(NSString*)accountId) {
```
[the remark this answers is not in the document]
Comment (piyush-kukadiya) [reply ios/CleverTapReact/CleverTapReact.mm:450]: Fixed in https://github.com/CleverTap/clevertap-react-native/pull/522/commits/c1de85bbc4df4f4b8729202f685c50cb2511130f. Traced in the iOS SDK (7.8.1, `CleverTap.m`): the class methods only persist a preference that is read once when the plist default config is built, while every getter checks its own instance's `config.enablePersonalization` — so the bridge methods never reached a secondary account, and did not even affect the default account within the current run. The bridge now flips `instance.config.enablePersonalization` on the resolved instance (immediate, per account, same as Android's instance methods, which set the same flag on the instance config) and keeps the class-method call for the default slot so the persisted preference and the next launch behave exactly as before.

File: src/index.js [hunk 13]
```diff
@@ -40,11 +51,551 @@ function callWithCallback(method, args, callback) {
...
+        //   handleB.addOneTimeListener(CleverTap.CleverTapProfileDidInitialize, (e) => ...);
+        // The subscription removes itself from inside the wrapper, so a second event
+        // can never fire the handler again. Mirrors CleverTap.addOneTimeListener.
+        addOneTimeListener: (eventName, handler) => {
+            const subscription = addListenerForHandle(accountId, eventName, (event) => {
+                handler(event);
+                subscription.remove();
+            });
+            return subscription;
+        },
```
[the remark this answers is not in the document]
Comment (piyush-kukadiya) [reply src/index.js]: Fixed in https://github.com/CleverTap/clevertap-react-native/pull/522/commits/729116cb3ef22087af9de9c88ffab3d779dfcc40: the four one-time wrappers are now one helper, `addOneTimeListenerForHandle`, which removes the subscription before invoking the handler, so a throwing handler (swallowed by `deliverRouted`) can no longer leave the wrapper registered.

File: src/index.js [hunk 14]
```diff
@@ -40,11 +51,551 @@ function callWithCallback(method, args, callback) {
...
+        currentDefaultAccountId = id;
+    }
+    routeDebug('default accountId resolved: ' + currentDefaultAccountId);
+    return currentDefaultAccountId;
+}).catch((error) => {
+    // Never swallow this silently: without the default account id, NO default-account
+    // event can be routed to top-level listeners.
+    console.warn('[CleverTap][MultiInstance] getDefaultAccountId failed — top-level listeners cannot receive events:', error);
+    return currentDefaultAccountId;
+});
```
[the remark this answers is not in the document]
Comment (piyush-kukadiya) [reply src/index.js]: Fixed in https://github.com/CleverTap/clevertap-react-native/pull/522/commits/f7154348c8cae6eed6e58157eb996211ef494b35: the import-time call is now guarded with a `typeof … === 'function'` check and falls back to a rejected promise that flows into the existing `.catch` (loud warning, `currentDefaultAccountId` fallback), so a native module without `getDefaultAccountId` (stale native build, partial Jest mock) no longer fails the whole SDK import.

File: android/src/main/java/com/clevertap/react/CleverTapModuleImpl.java [hunk 15]
```diff
@@ -1703,49 +1860,326 @@ private <T> HashMap<String, T> eventPropsFromReadableMap(ReadableMap propsMap, C
...
+        // sees, and identity cannot be repaired later from RN — so reject up front.
+        // Type-checked reads: a JS `null` arrives as ReadableType.Null, and getBoolean /
+        // getString would throw on it instead of reading "not set" (getType itself throws
+        // NoSuchKeyException on a missing key, hence the hasKey guard first).
+        boolean useCustomCleverTapId = config.hasKey("useCustomCleverTapId")
+                && config.getType("useCustomCleverTapId") == ReadableType.Boolean
+                && config.getBoolean("useCustomCleverTapId");
+        String cleverTapId = config.hasKey("cleverTapId")
+                && config.getType("cleverTapId") == ReadableType.String
+                ? config.getString("cleverTapId") : null;
```
[the remark this answers is not in the document]
Comment (piyush-kukadiya) [reply android/src/main/java/com/clevertap/react/CleverTapModuleImpl.java]: Fixed in https://github.com/CleverTap/clevertap-react-native/pull/522/commits/654c45876b55a5057da8ce4906cc202276a9e7bc, more broadly than the one field. Every `createInstance` config read on both platforms now goes through a parsing step that runs before any native work — `InstanceConfigRequest` (Kotlin) and its Objective-C twin `CleverTapReactInstanceConfigRequest` — with two rules: a JS `null` means "not set", and a value of the wrong type rejects the promise with `EINVALID` naming the field. On Android the parse happens on the calling thread and only `instanceWithConfig` runs on the main thread, so nothing can throw on the UI task anymore. Nine JVM tests cover null values, wrong types (including `"true"` for `useCustomCleverTapId`), credentials, the `cleverTapId` pairing and push-provider validation.

**Comment by piyush-kukadiya** [comment]
@coderabbitai review

File: android/src/main/java/com/clevertap/react/InstanceConfigRequest.kt [hunk 16]
```diff
@@ -0,0 +1,183 @@
...
+                region = optString(config, "region")?.takeIf { it.isNotBlank() },
+                proxyDomain = optString(config, "proxyDomain"),
+                spikyProxyDomain = optString(config, "spikyProxyDomain"),
+                identityKeys = optStringList(config, "identityKeys"),
+                handshakeDomain = optString(config, "handshakeDomain"),
+                logLevel = optString(config, "logLevel"),
+                analyticsOnly = optBoolean(config, "analyticsOnly"),
+                enablePersonalization = optBoolean(config, "enablePersonalization"),
+                disableAppLaunchedEvent = optBoolean(config, "disableAppLaunchedEvent"),
+                encryptionLevel = optString(config, "encryptionLevel"),
```
[the remark this answers is not in the document]
Comment (piyush-kukadiya) [reply android/src/main/java/com/clevertap/react/InstanceConfigRequest.kt]: Fixed in https://github.com/CleverTap/clevertap-react-native/pull/522/commits/d1399eab35bcadf276574e305de27ee9548ceb35: `logLevel` and `encryptionLevel` are now validated against the exact allowed words on both platforms (`optEnum` in the Kotlin parser, `ctReadEnum` in the Objective-C one) — off/info/debug/verbose and none/medium/high. A `null` stays "not set"; anything else rejects with `EINVALID` naming the field and the allowed values. JVM test added.

File: ios/CleverTapReact/CleverTapReactInstanceConfigRequest.m [hunk 17]
```diff
@@ -0,0 +1,127 @@
...
+}
+
+static NSString *ctReadString(NSDictionary *dict, NSString *key, NSString *prefix, NSString **error) {
+    return ctRead(dict, key, [NSString class], @"a string", prefix, error);
+}
+
+// JS booleans arrive as NSNumber — the only boxed class for them (see the header).
+static NSNumber *ctReadBool(NSDictionary *dict, NSString *key, NSString *prefix, NSString **error) {
+    return ctRead(dict, key, [NSNumber class], @"a boolean", prefix, error);
+}
```
[the remark this answers is not in the document]
Comment (piyush-kukadiya) [reply ios/CleverTapReact/CleverTapReactInstanceConfigRequest.m]: Fixed in https://github.com/CleverTap/clevertap-react-native/pull/522/commits/d1399eab35bcadf276574e305de27ee9548ceb35: `ctReadBool` now also requires `CFGetTypeID(...) == CFBooleanGetTypeID()`, so a JS number under a boolean key rejects with `EINVALID` on iOS exactly as Android's `ReadableType.Boolean` check does (the `__bridge` cast borrows the pointer, no retain-count change).
