### ISSUE TITLE
cannot find symbol  CleverTapAPI.setUIEditorConnectionEnabled(false);

### ISSUE THREAD

**Issue by arcsoft-bhanwar** [CleverTap/clevertap-react-native#162]
Hi Team CT,

I'm facing below issue while generating APK in react-native app.

``> Task :app:compileReleaseJavaWithJavac FAILED
D:\www\arcgatein\React_Native\cactus_react_native_app\Discovery\android\app\src\main\java\com\discovery\MainApplication.java:63: error: cannot find symbol
    CleverTapAPI.setUIEditorConnectionEnabled(false);
                ^
  symbol:   method setUIEditorConnectionEnabled(boolean)
  location: class CleverTapAPI
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 15s
468 actionable tasks: 2 executed, 466 up-to-date
error Command failed with exit code 1``

**It was working fine in react-native 0.63.4 but its not working for react-native 0.64.0**
"react": "17.0.1",
 "react-native": "0.64.1",
"clevertap-react-native": "^0.5.0",

**Comment by piyush-kukadiya** [comment]
duplicate of #161
